import { stringify } from "https://esm.sh/yaml@v2.3.1";
import WorkflowSpec, { JobSpec } from "./workflow_spec.ts";
import { EventSpec } from "./event.ts";

class Workflow {
  private yaml: WorkflowSpec;

  constructor(name: string) {
    this.yaml = {
      name,
      on: {},
      jobs: {},
    };
  }

  name(value: string) {
    this.yaml.name = value;
  }

  on(event: EventSpec): Workflow {
    this.yaml.on = event;
    return this;
  }

  withJob(jobId: string, job: JobSpec): Workflow {
    this.yaml.jobs[jobId] = job;
    return this;
  }

  jobs(value: { [jobId: string]: JobSpec }): Workflow {
    this.yaml.jobs = value;
    return this;
  }

  toString() {
    return `# Do not edit this file directly. It is generated by Fluent Github Actions\n\n${stringify(
      this.yaml
    )}`;
  }

  save(path: string) {
    const config = this.toString();
    Deno.writeTextFileSync(path, config);
  }
}

export default Workflow;
